const mockShrimpPrice = {
  "id": 5897,
  "species_id": 1,
  "date": "2024-04-29",
  "size_20": 99000,
  "size_30": 83000,
  "size_40": 76000,
  "size_50": 69000,
  "size_60": 66000,
  "size_70": 62000,
  "size_80": 57000,
  "size_90": 53000,
  "size_100": 52000,
  "size_110": null,
  "size_120": null,
  "size_130": null,
  "size_140": null,
  "size_150": null,
  "size_160": null,
  "size_170": null,
  "size_180": null,
  "size_190": null,
  "size_200": 0,
  "remark": null,
  "created_by": 10579,
  "updated_by": 53,
  "created_at": "2024-04-29 12:53:44",
  "updated_at": "2024-04-29 12:53:44",
  "region_id": "3402",
  "contact": "P**************la - +62**********8",
  "country_id": "ID",
  "currency_id": "IDR",
  "private": null,
  "week": 202418,
  "date_region_full_name": "2024-04-29 - DI YOGYAKARTA, BANTUL",
  "province_id": "34",
  "regency_id": "3402",
  "district_id": null,
  "village_id": null,
  "region": {
    "id": "3402",
    "name": "BANTUL",
    "type": null,
    "latitude": "-7.91901690",
    "longitude": "110.37854380",
    "country_id": "ID",
    "country_name": "Indonesia",
    "country_name_uppercase": "INDONESIA",
    "province_id": "34",
    "province_name": "DI YOGYAKARTA",
    "regency_id": "3402",
    "regency_name": "BANTUL",
    "district_id": null,
    "district_name": null,
    "village_id": null,
    "village_name": null,
    "full_name": "DI YOGYAKARTA, BANTUL",
    "name_translated": "BANTUL",
    "country_name_translated": "Indonesia",
    "country_name_translated_uppercase": "INDONESIA"
  },
  "creator": {
    "id": 10579,
    "role_id": 2,
    "name": "PanenUdang by Jala",
    "email": "panenhajibudhy@gmail.com",
    "avatar": "users/I6wH9Uaal4A4NEGUE2ILahJESnKEluyocJXSUMTJ.jpeg",
    "email_verified": true,
    "subscription_type_id": 1,
    "settings": {"locale": "id"},
    "created_at": "2021-01-21 01:03:45",
    "updated_at": "2023-06-28 01:18:23",
    "region_id": "34",
    "address": null,
    "last_login_at": "2021-06-21 01:19:18",
    "deactivated": false,
    "expired_at": null,
    "phone": "+6281393600068",
    "phone_verified": false,
    "gender": 1,
    "occupation": null,
    "id_number": null,
    "id_scan": null,
    "tin_number": null,
    "tin_scan": null,
    "birthdate": null,
    "company": null,
    "company_address": null,
    "position": null,
    "monthly_income": null,
    "income_source": null,
    "buyer": true,
    "phone_country": "ID",
    "country": "ID",
    "interest": "management",
    "unsubscribe_email_at": null,
    "freshchat_restore_id": null,
    "allow_create_client": true,
    "allow_create_token": false,
    "interests": ["management"],
    "state": {
      "phone_verification_expired_at": "2022-07-10 07:10:19",
      "mailjet_id": 3314417051,
      "partner": true,
      "consultation_tour_complete": true,
      "phone_verification_otp_sent": 0,
      "phone_updated_at": "2023-06-28 01:18:23"
    },
    "family_card_number": null,
    "family_card_scan": null,
    "telegram_id": null,
    "gender_name": "Laki-Laki",
    "expired_date": null,
    "expired_time": null,
    "upcoming_birthdate": null
  }
};

const mockShrimpPrice2 = {
  "id": 5898,
  "species_id": 1,
  "date": "2024-04-29",
  "size_20": 99000,
  "size_30": 83000,
  "size_40": 76000,
  "size_50": 69000,
  "size_60": 66000,
  "size_70": 62000,
  "size_80": 57000,
  "size_90": 53000,
  "size_100": 52000,
  "size_110": null,
  "size_120": null,
  "size_130": null,
  "size_140": null,
  "size_150": null,
  "size_160": null,
  "size_170": null,
  "size_180": null,
  "size_190": null,
  "size_200": 0,
  "remark": null,
  "created_by": 10579,
  "updated_by": 53,
  "created_at": "2024-04-29 12:53:44",
  "updated_at": "2024-04-29 12:53:44",
  "region_id": "3401",
  "contact": "P**************la - +62**********8",
  "country_id": "ID",
  "currency_id": "IDR",
  "private": null,
  "week": 202418,
  "date_region_full_name": "2024-04-29 - DI YOGYAKARTA, KULON PROGO",
  "province_id": "34",
  "regency_id": "3401",
  "district_id": null,
  "village_id": null,
  "region": {
    "id": "3401",
    "name": "KULON PROGO",
    "type": null,
    "latitude": "-7.82667980",
    "longitude": "110.16408460",
    "country_id": "ID",
    "country_name": "Indonesia",
    "country_name_uppercase": "INDONESIA",
    "province_id": "34",
    "province_name": "DI YOGYAKARTA",
    "regency_id": "3401",
    "regency_name": "KULON PROGO",
    "district_id": null,
    "district_name": null,
    "village_id": null,
    "village_name": null,
    "full_name": "DI YOGYAKARTA, KULON PROGO",
    "name_translated": "KULON PROGO",
    "country_name_translated": "Indonesia",
    "country_name_translated_uppercase": "INDONESIA"
  },
  "creator": {
    "id": 10579,
    "role_id": 2,
    "name": "PanenUdang by Jala",
    "email": "panenhajibudhy@gmail.com",
    "avatar": "users/I6wH9Uaal4A4NEGUE2ILahJESnKEluyocJXSUMTJ.jpeg",
    "email_verified": true,
    "subscription_type_id": 1,
    "settings": {"locale": "id"},
    "created_at": "2021-01-21 01:03:45",
    "updated_at": "2023-06-28 01:18:23",
    "region_id": "34",
    "address": null,
    "last_login_at": "2021-06-21 01:19:18",
    "deactivated": false,
    "expired_at": null,
    "phone": "+6281393600068",
    "phone_verified": false,
    "gender": 1,
    "occupation": null,
    "id_number": null,
    "id_scan": null,
    "tin_number": null,
    "tin_scan": null,
    "birthdate": null,
    "company": null,
    "company_address": null,
    "position": null,
    "monthly_income": null,
    "income_source": null,
    "buyer": true,
    "phone_country": "ID",
    "country": "ID",
    "interest": "management",
    "unsubscribe_email_at": null,
    "freshchat_restore_id": null,
    "allow_create_client": true,
    "allow_create_token": false,
    "interests": ["management"],
    "state": {
      "phone_verification_expired_at": "2022-07-10 07:10:19",
      "mailjet_id": 3314417051,
      "partner": true,
      "consultation_tour_complete": true,
      "phone_verification_otp_sent": 0,
      "phone_updated_at": "2023-06-28 01:18:23"
    },
    "family_card_number": null,
    "family_card_scan": null,
    "telegram_id": null,
    "gender_name": "Laki-Laki",
    "expired_date": null,
    "expired_time": null,
    "upcoming_birthdate": null
  }
};

const mockShrimpPriceReachedEnd = {
  "id": 2,
  "species_id": 1,
  "date": "2018-07-10",
  "size_20": null,
  "size_30": 88000,
  "size_40": 75000,
  "size_50": 67000,
  "size_60": 62000,
  "size_70": 60000,
  "size_80": 58000,
  "size_90": 55000,
  "size_100": 52000,
  "size_110": null,
  "size_120": null,
  "size_130": null,
  "size_140": null,
  "size_150": null,
  "size_160": null,
  "size_170": null,
  "size_180": null,
  "size_190": null,
  "size_200": null,
  "remark": null,
  "created_by": 205,
  "updated_by": 0,
  "created_at": "2018-08-01 09:40:05",
  "updated_at": "2021-04-07 06:48:54",
  "region_id": "3306",
  "contact": null,
  "country_id": "ID",
  "currency_id": "IDR",
  "private": null,
  "week": 201828,
  "date_region_full_name": "2018-07-10 - JAWA TENGAH, PURWOREJO",
  "province_id": "33",
  "regency_id": "3306",
  "district_id": null,
  "village_id": null,
  "region": {
    "id": "3306",
    "name": "PURWOREJO",
    "type": null,
    "latitude": "-7.69645090",
    "longitude": "109.99894160",
    "country_id": "ID",
    "country_name": "Indonesia",
    "country_name_uppercase": "INDONESIA",
    "province_id": "33",
    "province_name": "JAWA TENGAH",
    "regency_id": "3306",
    "regency_name": "PURWOREJO",
    "district_id": null,
    "district_name": null,
    "village_id": null,
    "village_name": null,
    "full_name": "JAWA TENGAH, PURWOREJO",
    "name_translated": "PURWOREJO",
    "country_name_translated": "Indonesia",
    "country_name_translated_uppercase": "INDONESIA"
  },
  "creator": {
    "id": 205,
    "role_id": 1,
    "name": "Endra",
    "email": "endraarifwicaksono@gmail.com",
    "avatar": "users/lXm12IwCoQtYRPgAGpUPc7h9IAxr8ecgSAZmLRl4.jpeg",
    "email_verified": true,
    "subscription_type_id": 1,
    "settings": {"locale": "id"},
    "created_at": "2018-11-06 04:11:37",
    "updated_at": "2024-05-01 14:24:15",
    "region_id": "34",
    "address": "Jala",
    "last_login_at": "2024-05-01 14:24:15",
    "deactivated": false,
    "expired_at": null,
    "phone": "+6282143331990",
    "phone_verified": true,
    "gender": 1,
    "occupation": "farm_technician",
    "id_number": null,
    "id_scan": null,
    "tin_number": null,
    "tin_scan": null,
    "birthdate": "1990-11-08",
    "company": null,
    "company_address": null,
    "position": null,
    "monthly_income": null,
    "income_source": null,
    "buyer": false,
    "phone_country": "ID",
    "country": null,
    "interest": "management",
    "unsubscribe_email_at": null,
    "freshchat_restore_id": null,
    "allow_create_client": true,
    "allow_create_token": true,
    "interests": ["management"],
    "state": {
      "export_import_tour_complete": true,
      "coachmark_shown": false,
      "phone_verification_expired_at": "2021-12-02 06:46:32",
      "create_cycle_tour_complete": true,
      "batch_list_tour_complete": true,
      "farm_list_tour_complete": true,
      "home_tour_complete": true,
      "input_excel_tour_complete": true,
      "add_cycle_modal_tour_complete": false,
      "add_feed_modal_tour_complete": false,
      "mortality_modal_tour_complete": false,
      "consultation_tour_complete": true,
      "treatment_modal_tour_complete": false,
      "mailjet_id": "1848121890",
      "disease_modal_tour_complete": false,
      "measurement_modal_tour_complete": false,
      "feed_tray_modal_tour_complete": false,
      "asset_introduction_complete": false,
      "home_coachmark_shown": true,
      "consultation_shown": "true",
      "financial_report_tour_complete": true,
      "cycle_to_do_shown": "true",
      "share_cultivation_tour_complete": true,
      "jala-event_shown": "true",
      "cost_per_pond_detail_tour_complete": true,
      "add_start_create_cycle_coachmark_shown": "true",
      "partner": false,
      "add_measurement_coachmark_shown": false,
      "add_create_farm_coachmark_shown": "true",
      "add_create_pond_coachmark_shown": "true",
      "add_feed_coachmark_shown": false,
      "add_feed_tray_coachmark_shown": false,
      "add_harvest_coachmark_shown": false,
      "khow_jala_from": null,
      "know_jala_from": "community",
      "sub_account_category_setting_tour_complete": true,
      "add_chemical_coachmark_shown": false,
      "add_disease_coachmark_shown": false,
      "auto_sync_stock_tour_complete": false,
      "harvest_modal_tour_complete": false,
      "sampling_modal_tour_complete": false,
      "add_treatment_coachmark_shown": false,
      "add_sampling_coachmark_shown": false,
      "sub_account_tour_complete": false,
      "import_finance_tour_complete": true,
      "home_new_feature_coachmark_shown": false,
      "home_new_feature_coachmark_1_4_7_shown": true,
      "home_graph_coachmark_shown": true,
      "chemical_prediction_coachmark_shown": true,
      "import_finance_complete": false
    },
    "family_card_number": null,
    "family_card_scan": null,
    "telegram_id": 607804110,
    "gender_name": "Laki-Laki",
    "expired_date": null,
    "expired_time": null,
    "upcoming_birthdate": "2024-11-08"
  }
};

const mockShrimpPrices = {
  "data": [mockShrimpPrice],
  "links": {
    "first":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=1",
    "last":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=5313",
    "prev": null,
    "next":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=2"
  },
  "meta": {
    "current_page": 1,
    "from": 1,
    "last_page": 5313,
    "path": "https://app.jala.tech/api/shrimp_prices",
    "per_page": "1",
    "to": 1,
    "total": 5313
  }
};

const mockShrimpPricesPage2 = {
  "data": [mockShrimpPrice2],
  "links": {
    "first":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=1",
    "last":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=5313",
    "prev":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=1",
    "next":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=3"
  },
  "meta": {
    "current_page": 2,
    "from": 2,
    "last_page": 5313,
    "path": "https://app.jala.tech/api/shrimp_prices",
    "per_page": "1",
    "to": 2,
    "total": 5313
  }
};

const mockShrimpPricesReachedEnd = {
  "data": [mockShrimpPriceReachedEnd],
  "links": {
    "first":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=1",
    "last":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=5313",
    "prev":
        "https://app.jala.tech/api/shrimp_prices?per_page=1&with=region%2Ccreator&page=5312",
    "next": null
  },
  "meta": {
    "current_page": 5313,
    "from": 5313,
    "last_page": 5313,
    "path": "https://app.jala.tech/api/shrimp_prices",
    "per_page": "1",
    "to": 5313,
    "total": 5313
  }
};
