const mockDetailShrimpPrices = {
  "data": {
    "id": 5897,
    "species_id": 1,
    "date": "2024-04-29",
    "size_20": 99000,
    "size_30": 83000,
    "size_40": 76000,
    "size_50": 69000,
    "size_60": 66000,
    "size_70": 62000,
    "size_80": 57000,
    "size_90": 53000,
    "size_100": 52000,
    "size_110": null,
    "size_120": null,
    "size_130": null,
    "size_140": null,
    "size_150": null,
    "size_160": null,
    "size_170": null,
    "size_180": null,
    "size_190": null,
    "size_200": 0,
    "remark": null,
    "created_by": 10579,
    "updated_by": 53,
    "created_at": "2024-04-29 12:53:44",
    "updated_at": "2024-04-29 12:53:44",
    "region_id": "3402",
    "contact": "P**************la - +62**********8",
    "country_id": "ID",
    "currency_id": "IDR",
    "private": null,
    "week": 202418,
    "date_region_full_name": "2024-04-29 - DI YOGYAKARTA, BANTUL",
    "province_id": "34",
    "regency_id": "3402",
    "district_id": null,
    "village_id": null,
    "region": {
      "id": "3402",
      "name": "BANTUL",
      "type": null,
      "latitude": "-7.91901690",
      "longitude": "110.37854380",
      "country_id": "ID",
      "country_name": "Indonesia",
      "country_name_uppercase": "INDONESIA",
      "province_id": "34",
      "province_name": "DI YOGYAKARTA",
      "regency_id": "3402",
      "regency_name": "BANTUL",
      "district_id": null,
      "district_name": null,
      "village_id": null,
      "village_name": null,
      "full_name": "DI YOGYAKARTA, BANTUL",
      "name_translated": "BANTUL",
      "country_name_translated": "Indonesia",
      "country_name_translated_uppercase": "INDONESIA"
    },
    "creator": {
      "id": 10579,
      "role_id": 2,
      "name": "PanenUdang by Jala",
      "email": "panenhajibudhy@gmail.com",
      "avatar": "users/I6wH9Uaal4A4NEGUE2ILahJESnKEluyocJXSUMTJ.jpeg",
      "email_verified": true,
      "subscription_type_id": 1,
      "settings": {"locale": "id"},
      "created_at": "2021-01-21 01:03:45",
      "updated_at": "2023-06-28 01:18:23",
      "region_id": "34",
      "address": null,
      "last_login_at": "2021-06-21 01:19:18",
      "deactivated": false,
      "expired_at": null,
      "phone": "+6281393600068",
      "phone_verified": false,
      "gender": 1,
      "occupation": null,
      "id_number": null,
      "id_scan": null,
      "tin_number": null,
      "tin_scan": null,
      "birthdate": null,
      "company": null,
      "company_address": null,
      "position": null,
      "monthly_income": null,
      "income_source": null,
      "buyer": true,
      "phone_country": "ID",
      "country": "ID",
      "interest": "management",
      "unsubscribe_email_at": null,
      "freshchat_restore_id": null,
      "allow_create_client": true,
      "allow_create_token": false,
      "interests": ["management"],
      "state": {
        "phone_verification_expired_at": "2022-07-10 07:10:19",
        "mailjet_id": 3314417051,
        "partner": true,
        "consultation_tour_complete": true,
        "phone_verification_otp_sent": 0,
        "phone_updated_at": "2023-06-28 01:18:23"
      },
      "family_card_number": null,
      "family_card_scan": null,
      "telegram_id": null,
      "gender_name": "Laki-Laki",
      "expired_date": null,
      "expired_time": null,
      "upcoming_birthdate": null
    }
  }
};

const mockResponseDetailShrimpPrices = {"data": mockDetailShrimpPrices};
